image: rockylinux/9
secrets:
  - 2a951cc8-a728-4dfc-947f-63fdb66e8fee
triggers:
  - action: email
    condition: failure
    to: Haowen Liu <lhw@lunacd.com>
tasks:
  - check_branch: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - setup: |
      sudo dnf module install -y nodejs:20
      sudo npm i -g corepack
  - deploy: |
      cd lxy-portfolio
      set +x
      source ~/.vercel_token
      yarn dlx -q vercel -t $VERCEL_TOKEN --yes --prod
      set -x
