import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_project_pages_blocks_title_bottom_margin_new" RENAME TO "enum_project_pages_blocks_title_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_text_bottom_margin_new" RENAME TO "enum_project_pages_blocks_text_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_horizontal_gallery_bottom_margin_new" RENAME TO "enum_project_pages_blocks_horizontal_gallery_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_image_bottom_margin_new" RENAME TO "enum_project_pages_blocks_image_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_youtube_bottom_margin_new" RENAME TO "enum_project_pages_blocks_youtube_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_document_bottom_margin_new" RENAME TO "enum_project_pages_blocks_document_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_text_image_bottom_margin_new" RENAME TO "enum_project_pages_blocks_text_image_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_horizontal_scroll_bottom_margin_new" RENAME TO "enum_project_pages_blocks_horizontal_scroll_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_slide_show_bottom_margin_new" RENAME TO "enum_project_pages_blocks_slide_show_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_small_gallery_bottom_margin_new" RENAME TO "enum_project_pages_blocks_small_gallery_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_equal_height_images_bottom_margin_new" RENAME TO "enum_project_pages_blocks_equal_height_images_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_large_gallery_bottom_margin_new" RENAME TO "enum_project_pages_blocks_large_gallery_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_column_bottom_margin_new" RENAME TO "enum_project_pages_blocks_column_bottom_margin";
  ALTER TYPE "public"."enum_project_pages_blocks_row_bottom_margin_new" RENAME TO "enum_project_pages_blocks_row_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_title_bottom_margin_new" RENAME TO "enum_blogs_blocks_title_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_text_bottom_margin_new" RENAME TO "enum_blogs_blocks_text_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_horizontal_gallery_bottom_margin_new" RENAME TO "enum_blogs_blocks_horizontal_gallery_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_image_bottom_margin_new" RENAME TO "enum_blogs_blocks_image_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_youtube_bottom_margin_new" RENAME TO "enum_blogs_blocks_youtube_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_document_bottom_margin_new" RENAME TO "enum_blogs_blocks_document_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_text_image_bottom_margin_new" RENAME TO "enum_blogs_blocks_text_image_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_horizontal_scroll_bottom_margin_new" RENAME TO "enum_blogs_blocks_horizontal_scroll_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_slide_show_bottom_margin_new" RENAME TO "enum_blogs_blocks_slide_show_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_small_gallery_bottom_margin_new" RENAME TO "enum_blogs_blocks_small_gallery_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_equal_height_images_bottom_margin_new" RENAME TO "enum_blogs_blocks_equal_height_images_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_large_gallery_bottom_margin_new" RENAME TO "enum_blogs_blocks_large_gallery_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_column_bottom_margin_new" RENAME TO "enum_blogs_blocks_column_bottom_margin";
  ALTER TYPE "public"."enum_blogs_blocks_row_bottom_margin_new" RENAME TO "enum_blogs_blocks_row_bottom_margin";
  ALTER TABLE "project_pages_blocks_title" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_text" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_horizontal_gallery" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_image" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_youtube" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_document" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_text_image" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_horizontal_scroll" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_slide_show" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_small_gallery" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_equal_height_images" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_large_gallery" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_column" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "project_pages_blocks_row" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_title" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_text" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_horizontal_gallery" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_image" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_youtube" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_document" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_text_image" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_horizontal_scroll" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_slide_show" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_small_gallery" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_equal_height_images" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_large_gallery" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_column" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";
  ALTER TABLE "blogs_blocks_row" RENAME COLUMN "bottom_margin_new" TO "bottom_margin";`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_project_pages_blocks_title_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_text_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_horizontal_gallery_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_image_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_youtube_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_document_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_text_image_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_horizontal_scroll_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_slide_show_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_small_gallery_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_equal_height_images_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_large_gallery_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_column_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_project_pages_blocks_row_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_title_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_text_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_horizontal_gallery_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_image_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_youtube_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_document_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_text_image_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_horizontal_scroll_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_slide_show_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_small_gallery_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_equal_height_images_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_large_gallery_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_column_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  CREATE TYPE "public"."enum_blogs_blocks_row_bottom_margin_new" AS ENUM('none', 'small', 'medium', 'regular', 'large', 'xl', 'xxl');
  ALTER TABLE "project_pages_blocks_title" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_title_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_text" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_text_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_horizontal_gallery" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_horizontal_gallery_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_image" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_image_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_youtube" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_youtube_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_document" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_document_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_text_image" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_text_image_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_horizontal_scroll" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_horizontal_scroll_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_slide_show" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_slide_show_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_small_gallery" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_small_gallery_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_equal_height_images" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_equal_height_images_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_large_gallery" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_large_gallery_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_column" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_column_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_row" ADD COLUMN "bottom_margin_new" "enum_project_pages_blocks_row_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_title" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_title_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_text" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_text_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_horizontal_gallery" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_horizontal_gallery_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_image" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_image_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_youtube" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_youtube_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_document" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_document_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_text_image" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_text_image_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_horizontal_scroll" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_horizontal_scroll_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_slide_show" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_slide_show_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_small_gallery" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_small_gallery_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_equal_height_images" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_equal_height_images_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_large_gallery" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_large_gallery_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_column" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_column_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "blogs_blocks_row" ADD COLUMN "bottom_margin_new" "enum_blogs_blocks_row_bottom_margin_new" DEFAULT 'xxl' NOT NULL;
  ALTER TABLE "project_pages_blocks_title" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_text" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_horizontal_gallery" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_image" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_youtube" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_document" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_text_image" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_horizontal_scroll" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_slide_show" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_small_gallery" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_equal_height_images" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_large_gallery" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_column" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "project_pages_blocks_row" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_title" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_text" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_horizontal_gallery" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_image" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_youtube" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_document" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_text_image" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_horizontal_scroll" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_slide_show" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_small_gallery" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_equal_height_images" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_large_gallery" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_column" DROP COLUMN IF EXISTS "bottom_margin";
  ALTER TABLE "blogs_blocks_row" DROP COLUMN IF EXISTS "bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_title_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_text_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_horizontal_gallery_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_image_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_youtube_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_document_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_text_image_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_horizontal_scroll_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_slide_show_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_small_gallery_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_equal_height_images_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_large_gallery_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_column_bottom_margin";
  DROP TYPE "public"."enum_project_pages_blocks_row_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_title_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_text_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_horizontal_gallery_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_image_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_youtube_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_document_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_text_image_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_horizontal_scroll_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_slide_show_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_small_gallery_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_equal_height_images_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_large_gallery_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_column_bottom_margin";
  DROP TYPE "public"."enum_blogs_blocks_row_bottom_margin";`)
}
