/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    document: Document;
    projects: Project;
    projectPages: ProjectPage;
    blogs: Blog;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    document: DocumentSelect<false> | DocumentSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    projectPages: ProjectPagesSelect<false> | ProjectPagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    global: Global;
  };
  globalsSelect: {
    global: GlobalSelect<false> | GlobalSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs?: {
    tasks: unknown;
    workflows?: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document".
 */
export interface Document {
  id: number;
  name: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  uri: string;
  order: number;
  subsetOrder: number;
  isMainProject: boolean;
  duration?: string | null;
  category: string;
  projectSize?: string | null;
  focuses?:
    | {
        focus: string;
        focusId: string;
        id?: string | null;
      }[]
    | null;
  brief?: string | null;
  projectImage?: (number | null) | Media;
  mobileProjectImage?: (number | null) | Media;
  projectGalleryImage: number | Media;
  backgroundColor?: string | null;
  pageBackgroundColor?: string | null;
  textColor: 'light' | 'dark';
  imageCover?: boolean | null;
  awardImage?: (number | null) | Media;
  externalLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectPages".
 */
export interface ProjectPage {
  id: number;
  projectName: string;
  blocks: (
    | {
        text: string;
        type: 'title' | 'subtitle';
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'title';
      }
    | {
        text: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'text';
      }
    | {
        items: {
          image: number | Media;
          text: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'horizontalGallery';
      }
    | {
        image: number | Media;
        imageSize: number;
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        embedLink: string;
        width: number;
        height: number;
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'youtube';
      }
    | {
        label: string;
        document: number | Document;
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'document';
      }
    | {
        title: string;
        text: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image: number | Media;
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textImage';
      }
    | {
        image: number | Media;
        scrollPrompt: string;
        width: number;
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'horizontalScroll';
      }
    | {
        images: {
          image: number | Media;
          id?: string | null;
        }[];
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'slideShow';
      }
    | {
        blocks: (
          | {
              text: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              textColor: 'dark' | 'light';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'text';
            }
          | {
              text: string;
              type: 'title' | 'subtitle';
              textColor: 'dark' | 'light';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'title';
            }
          | {
              image: number | Media;
              imageSize: number;
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'image';
            }
          | {
              blocks: (
                | {
                    text: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'text';
                  }
                | {
                    text: string;
                    type: 'title' | 'subtitle';
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'title';
                  }
                | {
                    image: number | Media;
                    imageSize: number;
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'image';
                  }
              )[];
              spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
              justify: 'start' | 'center' | 'end';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'column';
            }
          | {
              blocks: (
                | {
                    text: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'text';
                  }
                | {
                    text: string;
                    type: 'title' | 'subtitle';
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'title';
                  }
                | {
                    image: number | Media;
                    imageSize: number;
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'image';
                  }
              )[];
              spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'row';
            }
        )[];
        spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'row';
      }
    | {
        blocks: (
          | {
              text: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              textColor: 'dark' | 'light';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'text';
            }
          | {
              text: string;
              type: 'title' | 'subtitle';
              textColor: 'dark' | 'light';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'title';
            }
          | {
              image: number | Media;
              imageSize: number;
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'image';
            }
          | {
              blocks: (
                | {
                    text: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'text';
                  }
                | {
                    text: string;
                    type: 'title' | 'subtitle';
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'title';
                  }
                | {
                    image: number | Media;
                    imageSize: number;
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'image';
                  }
              )[];
              spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
              justify: 'start' | 'center' | 'end';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'column';
            }
          | {
              blocks: (
                | {
                    text: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'text';
                  }
                | {
                    text: string;
                    type: 'title' | 'subtitle';
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'title';
                  }
                | {
                    image: number | Media;
                    imageSize: number;
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'image';
                  }
              )[];
              spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'row';
            }
        )[];
        spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
        justify: 'start' | 'center' | 'end';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'column';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  date: string;
  blocks: (
    | {
        text: string;
        type: 'title' | 'subtitle';
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'title';
      }
    | {
        text: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'text';
      }
    | {
        items: {
          image: number | Media;
          text: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'horizontalGallery';
      }
    | {
        image: number | Media;
        imageSize: number;
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        embedLink: string;
        width: number;
        height: number;
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'youtube';
      }
    | {
        label: string;
        document: number | Document;
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'document';
      }
    | {
        title: string;
        text: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image: number | Media;
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textImage';
      }
    | {
        image: number | Media;
        scrollPrompt: string;
        width: number;
        textColor: 'dark' | 'light';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'horizontalScroll';
      }
    | {
        images: {
          image: number | Media;
          id?: string | null;
        }[];
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'slideShow';
      }
    | {
        blocks: (
          | {
              text: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              textColor: 'dark' | 'light';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'text';
            }
          | {
              text: string;
              type: 'title' | 'subtitle';
              textColor: 'dark' | 'light';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'title';
            }
          | {
              image: number | Media;
              imageSize: number;
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'image';
            }
          | {
              blocks: (
                | {
                    text: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'text';
                  }
                | {
                    text: string;
                    type: 'title' | 'subtitle';
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'title';
                  }
                | {
                    image: number | Media;
                    imageSize: number;
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'image';
                  }
              )[];
              spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
              justify: 'start' | 'center' | 'end';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'column';
            }
          | {
              blocks: (
                | {
                    text: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'text';
                  }
                | {
                    text: string;
                    type: 'title' | 'subtitle';
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'title';
                  }
                | {
                    image: number | Media;
                    imageSize: number;
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'image';
                  }
              )[];
              spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'row';
            }
        )[];
        spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'row';
      }
    | {
        blocks: (
          | {
              text: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              textColor: 'dark' | 'light';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'text';
            }
          | {
              text: string;
              type: 'title' | 'subtitle';
              textColor: 'dark' | 'light';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'title';
            }
          | {
              image: number | Media;
              imageSize: number;
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'image';
            }
          | {
              blocks: (
                | {
                    text: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'text';
                  }
                | {
                    text: string;
                    type: 'title' | 'subtitle';
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'title';
                  }
                | {
                    image: number | Media;
                    imageSize: number;
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'image';
                  }
              )[];
              spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
              justify: 'start' | 'center' | 'end';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'column';
            }
          | {
              blocks: (
                | {
                    text: {
                      root: {
                        type: string;
                        children: {
                          type: string;
                          version: number;
                          [k: string]: unknown;
                        }[];
                        direction: ('ltr' | 'rtl') | null;
                        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                        indent: number;
                        version: number;
                      };
                      [k: string]: unknown;
                    };
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'text';
                  }
                | {
                    text: string;
                    type: 'title' | 'subtitle';
                    textColor: 'dark' | 'light';
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'title';
                  }
                | {
                    image: number | Media;
                    imageSize: number;
                    bottomMargin: boolean;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'image';
                  }
              )[];
              spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
              bottomMargin: boolean;
              id?: string | null;
              blockName?: string | null;
              blockType: 'row';
            }
        )[];
        spacing: 'small' | 'medium' | 'regular' | 'large' | 'xl' | 'xxl';
        justify: 'start' | 'center' | 'end';
        bottomMargin: boolean;
        id?: string | null;
        blockName?: string | null;
        blockType: 'column';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'document';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'projectPages';
        value: number | ProjectPage;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document_select".
 */
export interface DocumentSelect<T extends boolean = true> {
  name?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  uri?: T;
  order?: T;
  subsetOrder?: T;
  isMainProject?: T;
  duration?: T;
  category?: T;
  projectSize?: T;
  focuses?:
    | T
    | {
        focus?: T;
        focusId?: T;
        id?: T;
      };
  brief?: T;
  projectImage?: T;
  mobileProjectImage?: T;
  projectGalleryImage?: T;
  backgroundColor?: T;
  pageBackgroundColor?: T;
  textColor?: T;
  imageCover?: T;
  awardImage?: T;
  externalLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectPages_select".
 */
export interface ProjectPagesSelect<T extends boolean = true> {
  projectName?: T;
  blocks?:
    | T
    | {
        title?:
          | T
          | {
              text?: T;
              type?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              text?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        horizontalGallery?:
          | T
          | {
              items?:
                | T
                | {
                    image?: T;
                    text?: T;
                    id?: T;
                  };
              spacing?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              imageSize?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        youtube?:
          | T
          | {
              embedLink?: T;
              width?: T;
              height?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        document?:
          | T
          | {
              label?: T;
              document?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        textImage?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        horizontalScroll?:
          | T
          | {
              image?: T;
              scrollPrompt?: T;
              width?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        slideShow?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        row?:
          | T
          | {
              blocks?:
                | T
                | {
                    text?:
                      | T
                      | {
                          text?: T;
                          textColor?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    title?:
                      | T
                      | {
                          text?: T;
                          type?: T;
                          textColor?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          image?: T;
                          imageSize?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    column?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                text?:
                                  | T
                                  | {
                                      text?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                title?:
                                  | T
                                  | {
                                      text?: T;
                                      type?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      imageSize?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          spacing?: T;
                          justify?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    row?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                text?:
                                  | T
                                  | {
                                      text?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                title?:
                                  | T
                                  | {
                                      text?: T;
                                      type?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      imageSize?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          spacing?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              spacing?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        column?:
          | T
          | {
              blocks?:
                | T
                | {
                    text?:
                      | T
                      | {
                          text?: T;
                          textColor?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    title?:
                      | T
                      | {
                          text?: T;
                          type?: T;
                          textColor?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          image?: T;
                          imageSize?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    column?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                text?:
                                  | T
                                  | {
                                      text?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                title?:
                                  | T
                                  | {
                                      text?: T;
                                      type?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      imageSize?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          spacing?: T;
                          justify?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    row?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                text?:
                                  | T
                                  | {
                                      text?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                title?:
                                  | T
                                  | {
                                      text?: T;
                                      type?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      imageSize?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          spacing?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              spacing?: T;
              justify?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  blocks?:
    | T
    | {
        title?:
          | T
          | {
              text?: T;
              type?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              text?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        horizontalGallery?:
          | T
          | {
              items?:
                | T
                | {
                    image?: T;
                    text?: T;
                    id?: T;
                  };
              spacing?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              imageSize?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        youtube?:
          | T
          | {
              embedLink?: T;
              width?: T;
              height?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        document?:
          | T
          | {
              label?: T;
              document?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        textImage?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        horizontalScroll?:
          | T
          | {
              image?: T;
              scrollPrompt?: T;
              width?: T;
              textColor?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        slideShow?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        row?:
          | T
          | {
              blocks?:
                | T
                | {
                    text?:
                      | T
                      | {
                          text?: T;
                          textColor?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    title?:
                      | T
                      | {
                          text?: T;
                          type?: T;
                          textColor?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          image?: T;
                          imageSize?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    column?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                text?:
                                  | T
                                  | {
                                      text?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                title?:
                                  | T
                                  | {
                                      text?: T;
                                      type?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      imageSize?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          spacing?: T;
                          justify?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    row?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                text?:
                                  | T
                                  | {
                                      text?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                title?:
                                  | T
                                  | {
                                      text?: T;
                                      type?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      imageSize?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          spacing?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              spacing?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
        column?:
          | T
          | {
              blocks?:
                | T
                | {
                    text?:
                      | T
                      | {
                          text?: T;
                          textColor?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    title?:
                      | T
                      | {
                          text?: T;
                          type?: T;
                          textColor?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          image?: T;
                          imageSize?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    column?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                text?:
                                  | T
                                  | {
                                      text?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                title?:
                                  | T
                                  | {
                                      text?: T;
                                      type?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      imageSize?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          spacing?: T;
                          justify?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                    row?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                text?:
                                  | T
                                  | {
                                      text?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                title?:
                                  | T
                                  | {
                                      text?: T;
                                      type?: T;
                                      textColor?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      imageSize?: T;
                                      bottomMargin?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          spacing?: T;
                          bottomMargin?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              spacing?: T;
              justify?: T;
              bottomMargin?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global".
 */
export interface Global {
  id: number;
  connectionPrompt: string;
  resume: number | Document;
  profile: string;
  profilePicture: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global_select".
 */
export interface GlobalSelect<T extends boolean = true> {
  connectionPrompt?: T;
  resume?: T;
  profile?: T;
  profilePicture?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}